### ISSUE TITLE
Input/Output Error

### ISSUE THREAD

**Issue by meganano202** [victorchall/EveryDream2trainer#100]
During the Training using [Google Colab version](https://colab.research.google.com/github/victorchall/EveryDream2trainer/blob/main/Train_Colab.ipynb) I'm getting the following error:

`Traceback (most recent call last):
File "/content/EveryDream2trainer/train.py", line 957, in <module>
    main(args)
  File "/content/EveryDream2trainer/train.py", line 883, in main
    raise ex
  File "/content/EveryDream2trainer/train.py", line 804, in main
    log_writer.add_scalar(tag="hyperparamater/lr", scalar_value=curr_lr, global_step=global_step)
  File "/usr/local/lib/python3.10/site-packages/torch/utils/tensorboard/writer.py", line 391, in add_scalar
    self._get_file_writer().add_summary(summary, global_step, walltime)
  File "/usr/local/lib/python3.10/site-packages/torch/utils/tensorboard/writer.py", line 113, in add_summary
    self.add_event(event, global_step, walltime)
  File "/usr/local/lib/python3.10/site-packages/torch/utils/tensorboard/writer.py", line 98, in add_event
    self.event_writer.add_event(event)
  File "/usr/local/lib/python3.10/site-packages/tensorboard/summary/writer/event_file_writer.py", line 117, in add_event
    self._async_writer.write(event.SerializeToString())
  File "/usr/local/lib/python3.10/site-packages/tensorboard/summary/writer/event_file_writer.py", line 171, in write
    self._check_worker_status()
  File "/usr/local/lib/python3.10/site-packages/tensorboard/summary/writer/event_file_writer.py", line 212, in _check_worker_status
    raise exception
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/site-packages/tensorboard/summary/writer/event_file_writer.py", line 244, in run
    self._run()
  File "/usr/local/lib/python3.10/
site-packages/tensorboard/summary/writer/event_file_writer.py", line 275, in _run
    self._record_writer.write(data)
  File "/usr/local/lib/python3.10/site-packages/tensorboard/summary/writer/record_writer.py", line 40, in write
    self._writer.write(header + header_crc + data + footer_crc)
  File "/usr/local/lib/python3.10/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 773, in write
    self.fs.append(self.filename, file_content, self.binary_mode)
  File "/usr/local/lib/python3.10/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 167, in append
    self._write(filename, file_content, "ab" if binary_mode else "a")
  File "/usr/local/lib/python3.10/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 171, in _write
    with io.open(filename, mode, encoding=encoding) as f:
OSError: [Errno 5] Input/output error`

I tought change the name of the images to process will solve it but didnt works

Maybe in this pic you can see the error better:
![260135e55c05a0dcdbf64c1703bdc805](https://user-images.githubusercontent.com/45272190/221990068-e231b147-97f2-4dc8-b467-81299b4446e7.png)

**Comment by victorchall** [comment]
Looks like a system error or disk problem.  I don't think this is a software issue.
