### ISSUE TITLE
[ERROR] bitsandbytes/cuda during installation

### ISSUE THREAD

**Issue by amrakm** [victorchall/EveryDream2trainer#179]
Installation crashes when it reaches bitsandbytes

```
*** Applying bitsandbytes patch for windows ***
 *** Already patched!
 *************************************************************
 *** bitsandbytes windows patch applied, attempting import ***
CUDA SETUP: Loading binary C:\Users\customer\Documents\EveryDream2trainer\venv\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
Somethnig went wrong trying to patch bitsandbytes, aborting
make sure your venv is activated and try again
or if activated try:
    pip install bitsandbytes==0.35.0
Traceback (most recent call last):
  File "C:\Users\customer\Documents\EveryDream2trainer\utils\[patch_bnb.py](http://patch_bnb.py/)", line 122, in main
    import bitsandbytes
  File "C:\Users\customer\Documents\EveryDream2trainer\venv\Lib\site-packages\bitsandbytes\[__init__.py](http://__init__.py/)", line 6, in <module>
    from .autograd._functions import (
  File "C:\Users\customer\Documents\EveryDream2trainer\venv\Lib\site-packages\bitsandbytes\autograd\[_functions.py](http://_functions.py/)", line 5, in <module>
    import bitsandbytes.functional as F
  File "C:\Users\customer\Documents\EveryDream2trainer\venv\Lib\site-packages\bitsandbytes\[functional.py](http://functional.py/)", line 13, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "C:\Users\customer\Documents\EveryDream2trainer\venv\Lib\site-packages\bitsandbytes\[cextension.py](http://cextension.py/)", line 41, in <module>
    lib = CUDALibrary_Singleton.get_instance().lib
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\customer\Documents\EveryDream2trainer\venv\Lib\site-packages\bitsandbytes\[cextension.py](http://cextension.py/)", line 37, in get_instance
    cls._instance.initialize()
  File "C:\Users\customer\Documents\EveryDream2trainer\venv\Lib\site-packages\bitsandbytes\[cextension.py](http://cextension.py/)", line 31, in initialize
    self.lib = ct.cdll.LoadLibrary(str(binary_path))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\ctypes\[__init__.py](http://__init__.py/)", line 454, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\ctypes\[__init__.py](http://__init__.py/)", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: Could not find module 'C:\Users\customer\Documents\EveryDream2trainer\venv\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll' (or one of its dependencies). Try using the full path with constructor syntax.```

**Comment by DirtyHamster** [comment]
Try the suggested line from the code: pip install bitsandbytes==0.35.0

**Comment by vanilla-coder** [comment]
I'm new to this trainer and made a fresh install according to instructions, which did not work, due to some problem with bitsandbytes/CUDA.

` UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.`

This makes the program fail with

`NameError: name 'str2optimizer8bit_blockwise' is not defined`

I've tried manually installing 0.35.0 as advised above, but this didn't solve the issue.

**Comment by victorchall** [comment]
The software now uses BNB 38.1. 

`pip install -U https://github.com/victorchall/everydream-whls/raw/main/bitsandbytes-0.38.1-py2.py3-none-any.whl`

**Comment by vanilla-coder** [comment]
Installing CUDA 11.8 solved my issue. Thanks for replying.

**Comment by victorchall** [comment]
@amrakm Try above solution to update BNB and install Cuda 11.8, should fix your issues.

When I push updates I post in #change-log channel on the discord with warnings if I update packages. Usually worst case is delete VENV folder and run windows setup again.
