### ISSUE TITLE
[BUG] Something went wrong trying to patch bitsandbytes

### ISSUE THREAD

**Issue by eliasts** [victorchall/EveryDream2trainer#181]
**Describe expected behavior and actual behavior**
Windows setup ends up with an error regarding bitsandbytes patching. (Latest commit)

**Attach log and cfg**
*** Applying bitsandbytes patch for windows ***
 *************************************************************
 *** bitsandbytes windows patch applied, attempting import ***
Somethnig went wrong trying to patch bitsandbytes, aborting
make sure your venv is activated and try again
or if activated try:
    pip install bitsandbytes==0.35.0
Traceback (most recent call last):
  File "K:\AI-APPS\EveryDream2trainer\utils\patch_bnb.py", line 122, in main
    import bitsandbytes
  File "K:\AI-APPS\EveryDream2trainer\venv\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "K:\AI-APPS\EveryDream2trainer\venv\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "K:\AI-APPS\EveryDream2trainer\venv\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "K:\AI-APPS\EveryDream2trainer\venv\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "K:\AI-APPS\EveryDream2trainer\venv\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "K:\AI-APPS\EveryDream2trainer\venv\lib\site-packages\bitsandbytes\cextension.py", line 28
    self.lib = ct.cdll.LoadLibrary(str(binary_path))
IndentationError: unexpected indent

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\AI-APPS\EveryDream2trainer\utils\patch_bnb.py", line 133, in <module>
    main()
  File "K:\AI-APPS\EveryDream2trainer\utils\patch_bnb.py", line 125, in main
    error()
  File "K:\AI-APPS\EveryDream2trainer\utils\patch_bnb.py", line 94, in error
    raise RuntimeError("** FATAL ERROR: unable to patch bitsandbytes for Windows env")
RuntimeError: ** FATAL ERROR: unable to patch bitsandbytes for Windows env
 downloaded: v2-inference-v.yaml
 downloaded: v2-inference.yaml
 downloaded: v1-inference.yaml
SD1.x and SD2.x yamls downloaded

**Runtime environment (please complete the following information):**
 - OS: Windows 10
 - GPU RTX 3060

**Comment by eliasts** [comment]
I had to modify the windows_setup.cmd script to revert back to bitsandbytes==0.35.0 in order to make it work again ...

**Comment by victorchall** [comment]
ED2 now uses BNB 38.1 and I setup a windows wheel for it.

Same answer as here: 

https://github.com/victorchall/EveryDream2trainer/issues/179#issuecomment-1586004230

Try git pull, run the updated pip install for BNB 38.1, and if you need from there install cuda 11.8.
