### ISSUE TITLE
[ERROR] I got a bitsandbytes error

### ISSUE THREAD

**Issue by MichaMaGit** [victorchall/EveryDream2trainer#195]
**Runtime environment (please complete the following information):**
 - OS: Win 10
 - GPU 3090 24GB

**Additional context**
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin D:\AI\EverDream_Trainer\EveryDream2trainer\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda112.dll
Traceback (most recent call last):
  File "D:\AI\EverDream_Trainer\EveryDream2trainer\train.py", line 934, in <module>
    main(args)
  File "D:\AI\EverDream_Trainer\EveryDream2trainer\train.py", line 573, in main
    ed_optimizer = EveryDreamOptimizer(args,
  File "D:\AI\EverDream_Trainer\EveryDream2trainer\optimizer\optimizers.py", line 64, in __init__
    self.optimizer_te, self.optimizer_unet = self.create_optimizers(args,
  File "D:\AI\EverDream_Trainer\EveryDream2trainer\optimizer\optimizers.py", line 148, in create_optimizers
    optimizer_te = self._create_optimizer("text encoder", args, self.te_config, text_encoder_params)
  File "D:\AI\EverDream_Trainer\EveryDream2trainer\optimizer\optimizers.py", line 359, in _create_optimizer
    import bitsandbytes as bnb
  File "D:\AI\EverDream_Trainer\EveryDream2trainer\venv\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>    from . import cuda_setup, utils, research
  File "D:\AI\EverDream_Trainer\EveryDream2trainer\venv\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "D:\AI\EverDream_Trainer\EveryDream2trainer\venv\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "D:\AI\EverDream_Trainer\EveryDream2trainer\venv\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "D:\AI\EverDream_Trainer\EveryDream2trainer\venv\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "D:\AI\EverDream_Trainer\EveryDream2trainer\venv\lib\site-packages\bitsandbytes\cextension.py", line 13, in <module>
    setup.run_cuda_setup()
  File "D:\AI\EverDream_Trainer\EveryDream2trainer\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py", line 145, in run_cuda_setup
    raise ex
  File "D:\AI\EverDream_Trainer\EveryDream2trainer\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py", line 138, in run_cuda_setup
    raise Exception('CUDA SETUP: Setup Failed!')
Exception: CUDA SETUP: Setup Failed!
[TEST-20230612-173058.log](https://github.com/victorchall/EveryDream2trainer/files/11725277/TEST-20230612-173058.log)
[logs.zip](https://github.com/victorchall/EveryDream2trainer/files/11725285/logs.zip)

**Comment by MichaMaGit** [comment]
Ok fixed it, installed new Cuda 11.8 and a BNB update.

https://github.com/victorchall/EveryDream2trainer/issues/179#issuecomment-1586004230
