### ISSUE TITLE
Failed to load checkpoint [ERROR]

### ISSUE THREAD

**Issue by velourlawsuits** [victorchall/EveryDream2trainer#206]
- OS: Windows 11
 - Local
 - RTX 4080 16GB

Here is the full stack trace:

D:\Stable Diffusion\EveryDream2trainer>call venv/scripts/activate.bat

(venv) D:\Stable Diffusion\EveryDream2trainer>python train.py --config train.json
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton.language'
** Your branch 'main' is up to date with the remote
Loading training config from train.json.
 * Windows detected, disabling Triton
 logging to logs\Mj1-20230629-032828.log
 Args:
{'amp': True,
 'aspects': [[960, 960],
             [1088, 832],
             [832, 1088],
             [1152, 768],
             [768, 1152],
             [1280, 704],
             [704, 1280],
             [1408, 640],
             [640, 1408],
             [1680, 576],
             [576, 1680],
             [1792, 512],
             [512, 1792],
             [2048, 448],
             [448, 2048]],
 'batch_size': 4,
 'ckpt_every_n_minutes': 1000000000.0,
 'clip_grad_norm': None,
 'clip_skip': 0,
 'cond_dropout': 0.04,
 'config': 'train.json',
 'data_root': 'D:\\Stable Diffusion\\EveryDream2trainer\\input\\Mj1',
 'disable_amp': False,
 'disable_textenc_training': False,
 'disable_unet_training': False,
 'disable_xformers': False,
 'flip_p': 0.0,
 'gpuid': 0,
 'grad_accum': 1,
 'gradient_checkpointing': True,
 'log_step': 1,
 'logdir': 'logs',
 'lowvram': False,
 'lr': 3e-07,
 'lr_decay_steps': 0,
 'lr_scheduler': 'constant',
 'lr_warmup_steps': 0,
 'max_epochs': 100,
 'no_prepend_last': False,
 'no_save_ckpt': False,
 'notebook': False,
 'optimizer_config': 'optimizer.json',
 'project_name': 'Mj1',
 'rated_dataset': False,
 'rated_dataset_target_dropout_percent': 50,
 'rated_dataset_target_dropout_rate': 50,
 'resolution': 960,
 'resume_ckpt': 'v1-5-pruned',
 'run_name': None,
 'sample_prompts': 'sample_prompts.txt',
 'sample_steps': 5000000,
 'save_ckpt_dir': None,
 'save_ckpts_from_n_epochs': 0,
 'save_every_n_epochs': 25,
 'save_full_precision': False,
 'save_optimizer': False,
 'scale_lr': False,
 'seed': 555,
 'shuffle_tags': False,
 'useadam8bit': False,
 'validation_config': 'validation_default.json',
 'wandb': False,
 'write_schedule': False,
 'zero_frequency_noise_ratio': 0.0}
 Seed: 555
Traceback (most recent call last):
  File "D:\Stable Diffusion\EveryDream2trainer\venv\lib\site-packages\huggingface_hub\utils\_errors.py", line 259, in hf_raise_for_status
    response.raise_for_status()
  File "D:\Stable Diffusion\EveryDream2trainer\venv\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/api/models/v1-5-pruned

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Stable Diffusion\EveryDream2trainer\train.py", line 452, in main
    downloaded = try_download_model_from_hf(repo_id=args.resume_ckpt)
  File "D:\Stable Diffusion\EveryDream2trainer\utils\huggingface_downloader.py", line 26, in try_download_model_from_hf
    model_info = huggingface_hub.model_info(repo_id)
  File "D:\Stable Diffusion\EveryDream2trainer\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\Stable Diffusion\EveryDream2trainer\venv\lib\site-packages\huggingface_hub\hf_api.py", line 1676, in model_info
    hf_raise_for_status(r)
  File "D:\Stable Diffusion\EveryDream2trainer\venv\lib\site-packages\huggingface_hub\utils\_errors.py", line 291, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-649d329e-08a285126056c925041253cb)

Repository Not Found for url: https://huggingface.co/api/models/v1-5-pruned.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.
 * Failed to load checkpoint *
Traceback (most recent call last):
  File "D:\Stable Diffusion\EveryDream2trainer\venv\lib\site-packages\huggingface_hub\utils\_errors.py", line 259, in hf_raise_for_status
    response.raise_for_status()
  File "D:\Stable Diffusion\EveryDream2trainer\venv\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/api/models/v1-5-pruned

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Stable Diffusion\EveryDream2trainer\train.py", line 941, in <module>
    main(args)
  File "D:\Stable Diffusion\EveryDream2trainer\train.py", line 452, in main
    downloaded = try_download_model_from_hf(repo_id=args.resume_ckpt)
  File "D:\Stable Diffusion\EveryDream2trainer\utils\huggingface_downloader.py", line 26, in try_download_model_from_hf
    model_info = huggingface_hub.model_info(repo_id)
  File "D:\Stable Diffusion\EveryDream2trainer\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\Stable Diffusion\EveryDream2trainer\venv\lib\site-packages\huggingface_hub\hf_api.py", line 1676, in model_info
    hf_raise_for_status(r)
  File "D:\Stable Diffusion\EveryDream2trainer\venv\lib\site-packages\huggingface_hub\utils\_errors.py", line 291, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-649d329e-08a285126056c925041253cb)

Repository Not Found for url: https://huggingface.co/api/models/v1-5-pruned.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.
[Mj1-20230629-032828.log](https://github.com/victorchall/EveryDream2trainer/files/11903172/Mj1-20230629-032828.log)

**Comment by velourlawsuits** [comment]
log: 06/29/2023 03:28:28 AM  Seed: 555
06/29/2023 03:28:28 AM  * Failed to load checkpoint *

config: {
  "config": "train.json",
  "amp": false,
  "batch_size": 4,
  "ckpt_every_n_minutes": null,
  "clip_grad_norm": null,
  "clip_skip": 0,
  "cond_dropout": 0.04,
  "data_root": "D:\\Stable Diffusion\\EveryDream2trainer\\input\\Mj1",
  "disable_textenc_training": false,
  "disable_xformers": false,
  "flip_p": 0.0,
  "gpuid": 0,
  "gradient_checkpointing": true,
  "grad_accum": 1,
  "logdir": "logs",
  "log_step": 1,
  "lowvram": false,
  "lr": 3e-07,
  "lr_decay_steps": 0,
  "lr_scheduler": "constant",
  "lr_warmup_steps": 0,
  "max_epochs": 100,
  "notebook": false,
  "optimizer_config": "optimizer.json",
  "project_name": "Mj1",
  "resolution": 960,
  "resume_ckpt": "v1-5-pruned",
  "run_name": null,
  "sample_prompts": "sample_prompts.txt",
  "sample_steps": 5000000,
  "save_ckpt_dir": null,
  "save_ckpts_from_n_epochs": 0,
  "save_every_n_epochs": 25,
  "save_optimizer": false,
  "scale_lr": false,
  "seed": 555,
  "shuffle_tags": false,
  "validation_config": "validation_default.json",
  "wandb": false,
  "write_schedule": false,
  "rated_dataset": false,
  "rated_dataset_target_dropout_percent": 50,
  "zero_frequency_noise_ratio": 0.0,
  "save_full_precision": false,
  "disable_unet_training": false,
  "rated_dataset_target_dropout_rate": 50,
  "disable_amp": false,
  "useadam8bit": false,
  "no_prepend_last": false,
  "no_save_ckpt": false
}
