### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'v2-1_768-nonema-pruned.ckpt'

### ISSUE THREAD

**Issue by Northloop** [victorchall/EveryDream2trainer#5]
After going through the install, I had some issues setting up.  The directories that you have in the image aren't there yet, so I decided to input the commands as you have them typed out and it looks like there's an issue with that directory not yet existing. I'm most interested in training SD2.1

(venv) C:\Users\micha\Documents\EveryDream2trainer>python utils/convert_original_stable_diffusion_to_diffusers.py --scheduler_type ddim ^
More? --original_config_file v2-inference-v.yaml ^
More? --image_size 768 ^
More? --checkpoint_path v2-1_768-nonema-pruned.ckpt ^
More? --prediction_type v_prediction ^
More? --upcast_attn False ^
More? --dump_path "ckpt_cache/v2-1_768-nonema-pruned"
Traceback (most recent call last):
  File "C:\Users\micha\Documents\EveryDream2trainer\utils\convert_original_stable_diffusion_to_diffusers.py", line 855, in <module>
    checkpoint = torch.load(args.checkpoint_path)
  File "C:\Users\micha\Documents\EveryDream2trainer\venv\lib\site-packages\torch\serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\micha\Documents\EveryDream2trainer\venv\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\micha\Documents\EveryDream2trainer\venv\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'v2-1_768-nonema-pruned.ckpt'

**Comment by victorchall** [comment]
It looks like it cannot find "v2-1_768-nonema-pruned.ckpt" in your /everydream2trainer folder.

You'll need to download that off huggingface or otherwise and put it in the /everydream2trainer folder first before running that command.

**Comment by Northloop** [comment]
Thank you for clearing this up for me.
