### ISSUE TITLE
RuntimeError: CUDA error: invalid argument with 1.5 and amp

### ISSUE THREAD

**Issue by UglyStupidHonest** [victorchall/EveryDream2trainer#70]
I get this error if I use SD 1.5 with amp 
RuntimeError: CUDA error: invalid argument

Is amp compatible with 1.5 ? 
Training setup
{
  "amp": true,
  "batch_size": 10,
  "ckpt_every_n_minutes": null,
  "clip_grad_norm": null,
  "clip_skip": 0,
  "cond_dropout": 0.04,
  "data_root": "captioned",
  "disable_textenc_training": false,
  "disable_xformers": false,
  "flip_p": 0.0,
  "gpuid": 0,
  "gradient_checkpointing": true,
  "grad_accum": 1,
  "logdir": "logs",
  "log_step": 25,
  "lowvram": false,
  "lr": 1.5e-06,
  "lr_decay_steps": 0,
  "lr_scheduler": "constant",
  "lr_warmup_steps": null,
  "max_epochs": 60,
  "notebook": false,
  "project_name": "prjctname",
  "resolution": 576,
  "resume_ckpt": "sd_v1-5_vae",
  "sample_prompts": "sample_prompts.txt",
  "sample_steps": 300,
  "save_ckpt_dir": null,
  "save_ckpts_from_n_epochs": 0,
  "save_every_n_epochs": 10,
  "save_optimizer": false,
  "scale_lr": false,
  "seed": 555,
  "shuffle_tags": false,
  "useadam8bit": true,
  "validation_config": "validation_default.json",
  "wandb": true,
  "write_schedule": false,
  "rated_dataset": false,
  "rated_dataset_target_dropout_percent": 50,
  "zero_frequency_noise_ratio": 0.0
}

full traceback

Traceback (most recent call last):
  File "/media/chris/Elements/ML_LAB/Everydream2.0/EveryDream2trainer/train.py", line 1044, in <module>
    main(args)
  File "/media/chris/Elements/ML_LAB/Everydream2.0/EveryDream2trainer/train.py", line 971, in main
    raise ex
  File "/media/chris/Elements/ML_LAB/Everydream2.0/EveryDream2trainer/train.py", line 860, in main
    scaler.scale(loss).backward()
  File "/media/chris/Elements/ML_LAB/Everydream2.0/EveryDream2trainer/env/lib/python3.10/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/media/chris/Elements/ML_LAB/Everydream2.0/EveryDream2trainer/env/lib/python3.10/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/media/chris/Elements/ML_LAB/Everydream2.0/EveryDream2trainer/env/lib/python3.10/site-packages/torch/autograd/function.py", line 253, in apply
    return user_fn(self, *args)
  File "/media/chris/Elements/ML_LAB/Everydream2.0/EveryDream2trainer/env/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 146, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "/media/chris/Elements/ML_LAB/Everydream2.0/EveryDream2trainer/env/lib/python3.10/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/media/chris/Elements/ML_LAB/Everydream2.0/EveryDream2trainer/env/lib/python3.10/site-packages/torch/autograd/function.py", line 253, in apply
    return user_fn(self, *args)
  File "/media/chris/Elements/ML_LAB/Everydream2.0/EveryDream2trainer/env/lib/python3.10/site-packages/torch/autograd/function.py", line 399, in wrapper
    outputs = fn(ctx, *args)
  File "/media/chris/Elements/ML_LAB/Everydream2.0/EveryDream2trainer/env/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 107, in backward
    grads = _memory_efficient_attention_backward(
  File "/media/chris/Elements/ML_LAB/Everydream2.0/EveryDream2trainer/env/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 380, in _memory_efficient_attention_backward
    grads = op.apply(ctx, inp, grad)
  File "/media/chris/Elements/ML_LAB/Everydream2.0/EveryDream2trainer/env/lib/python3.10/site-packages/xformers/ops/fmha/cutlass.py", line 283, in apply
    (grad_q, grad_k, grad_v, grad_bias) = cls.OPERATOR(
  File "/media/chris/Elements/ML_LAB/Everydream2.0/EveryDream2trainer/env/lib/python3.10/site-packages/torch/_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by victorchall** [comment]
Something is wrong with your package installs...  Are you using qslug's container?

ED2 should work with both SD1.4/1.5, SD2.0-base, and SD2.1-768

**Comment by UglyStupidHonest** [comment]
I installed this myself on ubuntu might have done a terrible mistake :) The SD 2 models work fine maybe its xformers . I need 1.5 though for the control net goods ! Thank you ! I will try the container

**Comment by nawnie** [comment]
try with newest update :D

**Comment by UglyStupidHonest** [comment]
Ohh ! I will thank you :)

**Comment by qslug** [comment]
Yeah, getting the right mix of dependencies up and running in Ubuntu is not a simple matter. The latest RunPod template (https://runpod.io/gsc?template=d1v63jb36t&ref=bbp9dh8x) has all of the kinks worked out. I have definitely seen that error as part of getting the dependencies hashed out; some incompatibility between torch, cuda toolkit, and xformers most likely.

**Comment by victorchall** [comment]
Did you figure this out or update to the newest docker container?

**Comment by nrgaway** [comment]
This conda environment works for me with Debian bookworm.  Note that `pyre-extensions` had to be at version `0.0.23` (`0.0.30` did not work).

**environment.yml**
```
# conda env update
name: everydream-trainer
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - torchvision=0.14.1

  - aiohttp=3.8.4
  - diffusers>=0.13.0
  - ftfy=6.1.1
  - numpy=1.23.5
  - protobuf=3.20.3
  - tensorboard>=2.11.0
  - scipy
  - pip:
    - accelerate
    - bitsandbytes==0.37.0
    - lion-pytorch
    - omegaconf==2.2.3
    - pynvml==11.5.0
    - pyre-extensions==0.0.23
    - pytorch-lightning==1.9.2
    - setuptools
    - transformers==4.25.1
    - triton>=2.0.0a2
    - wandb==0.13.6
    - xformers>=0.0.17.dev451
```
