### ISSUE TITLE
Initial checkpoint conversion error

### ISSUE THREAD

**Issue by egormly** [victorchall/EveryDream2trainer#89]
I get this when installing via YT tutorial. All other steps were followed. I have the correct files in the root dir.

(venv) D:\EveryDream2\EveryDream2trainer>python utils/convert_original_stable_diffusion_to_diffusers.py --scheduler_type ddim ^
More? --original_config_file v1-inference.yaml ^
More? --image_size 512 ^
More? --checkpoint_path sd_v1-5_vae.ckpt ^
More? --prediction_type epsilon ^
More? --upcast_attn False ^
More? --dump_path "ckpt_cache/sd_v1-5_vae"
Traceback (most recent call last):
  File "D:\EveryDream2\EveryDream2trainer\utils\convert_original_stable_diffusion_to_diffusers.py", line 854, in <module>
    checkpoint = torch.load(args.checkpoint_path)
  File "D:\EveryDream2\EveryDream2trainer\venv\lib\site-packages\torch\serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "D:\EveryDream2\EveryDream2trainer\venv\lib\site-packages\torch\serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.

**Comment by victorchall** [comment]
Might try downloading the file again, maybe corrupt?

**Comment by egormly** [comment]
Thank you,  solved!  that was.. odd.   I haven't had a corrupted ckpt before.
