### ISSUE TITLE
Memory allocation

### ISSUE THREAD

**Issue by lelapin123** [victorchall/EveryDream2trainer#91]
My graphic card has only 6GB of memory and when i try to run a training session, i receive the following answer:

omething went wrong, attempting to save model                                                   | 0/12 [00:00<?, ?it/s]
  No model to save, something likely blew up on startup, not saving
Traceback (most recent call last):
  File "D:\download\AI\EveryDream2trainer\train.py", line 1050, in <module>
    main(args)
  File "D:\download\AI\EveryDream2trainer\train.py", line 977, in main
    raise ex
  File "D:\download\AI\EveryDream2trainer\train.py", line 854, in main
    model_pred, target = get_model_prediction_and_target(batch["image"], batch["tokens"], args.zero_frequency_noise_ratio)
  File "D:\download\AI\EveryDream2trainer\train.py", line 779, in get_model_prediction_and_target
    latents = vae.encode(pixel_values, return_dict=False)
  File "D:\download\AI\EveryDream2trainer\venv\lib\site-packages\diffusers\models\vae.py", line 566, in encode
    h = self.encoder(x)
  File "D:\download\AI\EveryDream2trainer\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\download\AI\EveryDream2trainer\venv\lib\site-packages\diffusers\models\vae.py", line 134, in forward
    sample = down_block(sample)
  File "D:\download\AI\EveryDream2trainer\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\download\AI\EveryDream2trainer\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 755, in forward
    hidden_states = resnet(hidden_states, temb=None)
  File "D:\download\AI\EveryDream2trainer\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\download\AI\EveryDream2trainer\venv\lib\site-packages\diffusers\models\resnet.py", line 450, in forward
    hidden_states = self.norm1(hidden_states)
  File "D:\download\AI\EveryDream2trainer\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\download\AI\EveryDream2trainer\venv\lib\site-packages\torch\nn\modules\normalization.py", line 272, in forward
    return F.group_norm(
  File "D:\download\AI\EveryDream2trainer\venv\lib\site-packages\torch\nn\functional.py", line 2516, in group_norm
    return torch.group_norm(input, num_groups, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: CUDA out of memory. Tried to allocate 720.00 MiB (GPU 0; 6.00 GiB total capacity; 4.71 GiB already allocated; 0 bytes free; 4.80 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Is there any way to fix the problem ?
What solution do i have ?

**Comment by ShadoWxShinigamI** [comment]
unfortunately, i believe you need a minimum of 12gb VRAM to run training locally. Try using the colab version

**Comment by victorchall** [comment]
Colab free tier works, but yes, I think the lowest anyone has gotten training to work is 11GB but just barely.  

There are few options with 6GB, I think LORA works on 8GB, but EveryDream is likely sticking with full fine tuning and will not be adding LORA.

**Comment by lelapin123** [comment]
The problem is really a lack of memory on the graphic card.
I can make it work on the same system with a better graphic card.
